/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author user
 */
public class pasta extends javax.swing.JFrame {

    /**
     * Creates new form pasta
     */
    public pasta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        areaTxt = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        CrispyBaconGarlicSolo = new javax.swing.JCheckBox();
        ChickenMushroomSpinach = new javax.swing.JCheckBox();
        ChickenPestoLinguinPasta = new javax.swing.JCheckBox();
        CrispyBaconGarlicParsleyLarge = new javax.swing.JCheckBox();
        ChickenMushroomSpinachLarge = new javax.swing.JCheckBox();
        ChickenPestoLinguinePastaLarge = new javax.swing.JCheckBox();
        cripybaconsoloprice = new javax.swing.JLabel();
        chickenmushroomsolo = new javax.swing.JLabel();
        chickenpestosolo = new javax.swing.JLabel();
        crispybaconlarge = new javax.swing.JLabel();
        chickenmushroomlarge = new javax.swing.JLabel();
        chickenpestolarge = new javax.swing.JLabel();
        pastabutton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        pastapcs = new javax.swing.JTextField();
        pastaofitaly = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Serif", 3, 48)); // NOI18N
        jLabel1.setText("Pasta");

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        areaTxt.setViewportView(jTextArea1);

        CrispyBaconGarlicSolo.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        CrispyBaconGarlicSolo.setText("Crispy Bacon Garlic & Parsley Linguine Pasta (Solo)");
        CrispyBaconGarlicSolo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrispyBaconGarlicSoloActionPerformed(evt);
            }
        });

        ChickenMushroomSpinach.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        ChickenMushroomSpinach.setText("Chicken Mushroom & Spinach Fettucine Pasta (Solo)");
        ChickenMushroomSpinach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChickenMushroomSpinachActionPerformed(evt);
            }
        });

        ChickenPestoLinguinPasta.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        ChickenPestoLinguinPasta.setText("Chicken Pesto Linguine Pasta (Solo)");
        ChickenPestoLinguinPasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChickenPestoLinguinPastaActionPerformed(evt);
            }
        });

        CrispyBaconGarlicParsleyLarge.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        CrispyBaconGarlicParsleyLarge.setText("Crispy Bacon Garlic & Parsley Linguine Pasta (Large)");
        CrispyBaconGarlicParsleyLarge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrispyBaconGarlicParsleyLargeActionPerformed(evt);
            }
        });

        ChickenMushroomSpinachLarge.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        ChickenMushroomSpinachLarge.setText("Chicken Mushroom & Spinach Fettucine Pasta (Large)");
        ChickenMushroomSpinachLarge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChickenMushroomSpinachLargeActionPerformed(evt);
            }
        });

        ChickenPestoLinguinePastaLarge.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        ChickenPestoLinguinePastaLarge.setText("Chicken Pesto Linguine Pasta (Large)");
        ChickenPestoLinguinePastaLarge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChickenPestoLinguinePastaLargeActionPerformed(evt);
            }
        });

        cripybaconsoloprice.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        cripybaconsoloprice.setText("PHP 159.99");

        chickenmushroomsolo.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        chickenmushroomsolo.setText("PHP 159.99");

        chickenpestosolo.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        chickenpestosolo.setText("PHP 159.99");

        crispybaconlarge.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        crispybaconlarge.setText("PHP 289.99");

        chickenmushroomlarge.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        chickenmushroomlarge.setText("PHP 289.99");

        chickenpestolarge.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        chickenpestolarge.setText("PHP 289.99");

        pastabutton.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        pastabutton.setText("Done");
        pastabutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pastabuttonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Serif", 3, 12)); // NOI18N
        jLabel2.setText("pcs:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(pastapcs, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(126, 126, 126)
                            .addComponent(pastabutton))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(CrispyBaconGarlicSolo)
                                .addComponent(ChickenMushroomSpinach)
                                .addComponent(ChickenPestoLinguinPasta)
                                .addComponent(CrispyBaconGarlicParsleyLarge)
                                .addComponent(ChickenMushroomSpinachLarge)
                                .addComponent(ChickenPestoLinguinePastaLarge))
                            .addGap(58, 58, 58)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cripybaconsoloprice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(chickenmushroomsolo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(chickenpestosolo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(crispybaconlarge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(chickenmushroomlarge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(chickenpestolarge, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(areaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CrispyBaconGarlicSolo)
                    .addComponent(cripybaconsoloprice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChickenMushroomSpinach)
                    .addComponent(chickenmushroomsolo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChickenPestoLinguinPasta)
                    .addComponent(chickenpestosolo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CrispyBaconGarlicParsleyLarge)
                    .addComponent(crispybaconlarge))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChickenMushroomSpinachLarge)
                    .addComponent(chickenmushroomlarge))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChickenPestoLinguinePastaLarge)
                    .addComponent(chickenpestolarge))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pastabutton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(pastapcs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(areaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        pastaofitaly.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        pastaofitaly.setText("Pasta of Italy evolved according to the British palate");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(pastaofitaly))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(pastaofitaly)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CrispyBaconGarlicSoloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrispyBaconGarlicSoloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CrispyBaconGarlicSoloActionPerformed

    private void ChickenMushroomSpinachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChickenMushroomSpinachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChickenMushroomSpinachActionPerformed

    private void ChickenPestoLinguinPastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChickenPestoLinguinPastaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChickenPestoLinguinPastaActionPerformed

    private void CrispyBaconGarlicParsleyLargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrispyBaconGarlicParsleyLargeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CrispyBaconGarlicParsleyLargeActionPerformed

    private void ChickenMushroomSpinachLargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChickenMushroomSpinachLargeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChickenMushroomSpinachLargeActionPerformed

    private void ChickenPestoLinguinePastaLargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChickenPestoLinguinePastaLargeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChickenPestoLinguinePastaLargeActionPerformed

    private void pastabuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pastabuttonActionPerformed
        // TODO add your handling code here:
        StringBuilder summary = new StringBuilder();
    double total = 0;

    // Get the number of pieces entered
    int pcs;
    try {
        pcs = Integer.parseInt(pastapcs.getText());
    } catch (NumberFormatException e) {
        pcs = 0; // Default to 0 if input is invalid
    }

    // Check which items are selected and build the summary
    if (CrispyBaconGarlicSolo.isSelected()) {
        summary.append("Crispy Bacon Garlic & Parsley Linguine Pasta (Solo): ").append(pcs).append(" pcs at ₱ 159.99 each\n");
        total += pcs * 159.99;
    }
    if (ChickenMushroomSpinach.isSelected()) {
        summary.append("Chicken Mushroom & Spinach Fettucine Pasta (Solo): ").append(pcs).append(" pcs at ₱ 159.99 each\n");
        total += pcs * 159.99;
    }
    if (ChickenPestoLinguinPasta.isSelected()) {
        summary.append("Chicken Pesto Linguine Pasta (Solo): ").append(pcs).append(" pcs at ₱ 159.99 each\n");
        total += pcs * 159.99;
    }
    if (CrispyBaconGarlicParsleyLarge.isSelected()) {
        summary.append("Crispy Bacon Garlic & Parsley Linguine Pasta (Large): ").append(pcs).append(" pcs at ₱ 289.99 each\n");
        total += pcs * 289.99;
    }
    if (ChickenMushroomSpinachLarge.isSelected()) {
        summary.append("Chicken Mushroom & Spinach Fettucine Pasta (Large): ").append(pcs).append(" pcs at ₱ 289.99 each\n");
        total += pcs * 289.99;
    }
    if (ChickenPestoLinguinePastaLarge.isSelected()) {
        summary.append("Chicken Pesto Linguine Pasta (Large): ").append(pcs).append(" pcs at ₱ 289.99 each\n");
        total += pcs * 289.99;
    }

    // Append the total to the summary
    summary.append("Total: ₱ ").append(total).append("\n");

    // Display the summary in the JTextArea
    jTextArea1.setText(summary.toString());
    }//GEN-LAST:event_pastabuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pasta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pasta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pasta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pasta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pasta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ChickenMushroomSpinach;
    private javax.swing.JCheckBox ChickenMushroomSpinachLarge;
    private javax.swing.JCheckBox ChickenPestoLinguinPasta;
    private javax.swing.JCheckBox ChickenPestoLinguinePastaLarge;
    private javax.swing.JCheckBox CrispyBaconGarlicParsleyLarge;
    private javax.swing.JCheckBox CrispyBaconGarlicSolo;
    private javax.swing.JScrollPane areaTxt;
    private javax.swing.JLabel chickenmushroomlarge;
    private javax.swing.JLabel chickenmushroomsolo;
    private javax.swing.JLabel chickenpestolarge;
    private javax.swing.JLabel chickenpestosolo;
    private javax.swing.JLabel cripybaconsoloprice;
    private javax.swing.JLabel crispybaconlarge;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton pastabutton;
    private javax.swing.JLabel pastaofitaly;
    private javax.swing.JTextField pastapcs;
    // End of variables declaration//GEN-END:variables
}
