/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author user
 */
public class room extends javax.swing.JFrame {

    private String selectedRoomType;
    private int numberOfPax;

    public room() {
        initComponents();
    }

    // Getter for selectedRoomType
    public String getSelectedRoomType() {
        return selectedRoomType;
    }
    
    
    // Setter for selectedRoomType
    public void setSelectedRoomType(String selectedRoomType) {
        this.selectedRoomType = selectedRoomType;
    }
    
    // Getter for numberOfPax
    public int getNumberOfPax() {
        return numberOfPax;
    }
    
    // Setter for numberOfPax
    public void setNumberOfPax(int numberOfPax) {
        this.numberOfPax = numberOfPax;
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        roomreserve = new javax.swing.JLabel();
        plschoose = new javax.swing.JLabel();
        guestchoice = new javax.swing.JLabel();
        choice = new javax.swing.JLabel();
        singleroom = new javax.swing.JRadioButton();
        standardroom = new javax.swing.JLabel();
        doubleroom = new javax.swing.JRadioButton();
        twinroom = new javax.swing.JRadioButton();
        pax = new javax.swing.JLabel();
        numberofpax = new javax.swing.JTextField();
        prices = new javax.swing.JLabel();
        singleprice = new javax.swing.JLabel();
        doubleprice = new javax.swing.JLabel();
        twinprice = new javax.swing.JLabel();
        deluxeroom = new javax.swing.JLabel();
        premiumfurnish = new javax.swing.JRadioButton();
        wbalcony = new javax.swing.JRadioButton();
        viewofresort = new javax.swing.JRadioButton();
        premprice = new javax.swing.JLabel();
        wbalconyprice = new javax.swing.JLabel();
        viewprice = new javax.swing.JLabel();
        suiteroom = new javax.swing.JLabel();
        junior = new javax.swing.JRadioButton();
        executive = new javax.swing.JRadioButton();
        presidential = new javax.swing.JRadioButton();
        royal = new javax.swing.JRadioButton();
        juniorprice = new javax.swing.JLabel();
        executiveprice = new javax.swing.JLabel();
        presidentialprice = new javax.swing.JLabel();
        royalprice = new javax.swing.JLabel();
        done = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        result = new javax.swing.JTextArea();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        roomreserve.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        roomreserve.setText("Room Reservation");

        plschoose.setFont(new java.awt.Font("SansSerif", 2, 10)); // NOI18N
        plschoose.setText("Please choose your desired Room Type");

        guestchoice.setFont(new java.awt.Font("Serif", 3, 12)); // NOI18N
        guestchoice.setText("Guest's choice of Room Type:");

        choice.setFont(new java.awt.Font("Serif", 3, 12)); // NOI18N
        choice.setText("Choices:");

        buttonGroup1.add(singleroom);
        singleroom.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        singleroom.setText("Single Room");
        singleroom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                singleroomActionPerformed(evt);
            }
        });

        standardroom.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        standardroom.setText("Standard Room");

        buttonGroup1.add(doubleroom);
        doubleroom.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        doubleroom.setText("Double Room");
        doubleroom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doubleroomActionPerformed(evt);
            }
        });

        buttonGroup1.add(twinroom);
        twinroom.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        twinroom.setText("Twin Room");
        twinroom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twinroomActionPerformed(evt);
            }
        });

        pax.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        pax.setText("Pax:");

        numberofpax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberofpaxActionPerformed(evt);
            }
        });

        prices.setFont(new java.awt.Font("Serif", 3, 12)); // NOI18N
        prices.setText("Prices:");

        singleprice.setText("PHP 1,000");

        doubleprice.setText("PHP 2,500");

        twinprice.setText("PHP 2,800 ");

        deluxeroom.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        deluxeroom.setText("Deluxe Room");

        buttonGroup1.add(premiumfurnish);
        premiumfurnish.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        premiumfurnish.setText("Premium Furnishing");
        premiumfurnish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                premiumfurnishActionPerformed(evt);
            }
        });

        buttonGroup1.add(wbalcony);
        wbalcony.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        wbalcony.setText("W/ Balcony or Patio");
        wbalcony.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wbalconyActionPerformed(evt);
            }
        });

        buttonGroup1.add(viewofresort);
        viewofresort.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        viewofresort.setText("View of Resort");
        viewofresort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewofresortActionPerformed(evt);
            }
        });

        premprice.setText("PHP 6,000");

        wbalconyprice.setText("PHP 6,500");

        viewprice.setText("PHP 7,000");

        suiteroom.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        suiteroom.setText("Suite Room");

        buttonGroup1.add(junior);
        junior.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        junior.setText("Junior Room");
        junior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                juniorActionPerformed(evt);
            }
        });

        buttonGroup1.add(executive);
        executive.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        executive.setText("Executive Room");
        executive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                executiveActionPerformed(evt);
            }
        });

        buttonGroup1.add(presidential);
        presidential.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        presidential.setText("Presidential Room");
        presidential.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                presidentialActionPerformed(evt);
            }
        });

        buttonGroup1.add(royal);
        royal.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        royal.setText("Royal");
        royal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                royalActionPerformed(evt);
            }
        });

        juniorprice.setText("PHP 8,000");

        executiveprice.setText("PHP 8,500");

        presidentialprice.setText("PHP 9,000");

        royalprice.setText("PHP 9,500");

        done.setText("Done");
        done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        jLabel1.setText("Summary of Reservation");

        submit.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        result.setColumns(20);
        result.setRows(5);
        jScrollPane3.setViewportView(result);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(guestchoice)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(submit)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(6, 6, 6)
                                                        .addComponent(pax)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(numberofpax, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(deluxeroom)
                                                    .addComponent(standardroom, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(suiteroom, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel1)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(choice)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                            .addGap(23, 23, 23)
                                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(singleroom, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(doubleroom, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(twinroom, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addComponent(premiumfurnish, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(wbalcony, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(viewofresort, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(24, 24, 24)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(executive, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(junior, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(royal, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(presidential, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addGap(35, 35, 35)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(done)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(prices)
                                                        .addComponent(singleprice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(doubleprice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(twinprice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(premprice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(wbalconyprice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(viewprice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(juniorprice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(executiveprice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(presidentialprice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(royalprice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(121, 121, 121)
                            .addComponent(roomreserve))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(96, 96, 96)
                            .addComponent(plschoose))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(roomreserve)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(plschoose)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(guestchoice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(choice)
                    .addComponent(prices))
                .addGap(11, 11, 11)
                .addComponent(standardroom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(singleroom)
                    .addComponent(singleprice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doubleprice)
                    .addComponent(doubleroom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(twinprice)
                    .addComponent(twinroom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deluxeroom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(premiumfurnish)
                    .addComponent(premprice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wbalcony)
                    .addComponent(wbalconyprice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewprice)
                    .addComponent(viewofresort, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(suiteroom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(junior)
                    .addComponent(juniorprice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(executiveprice)
                    .addComponent(executive))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(presidentialprice)
                    .addComponent(presidential))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(royalprice)
                    .addComponent(royal, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numberofpax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(done)
                        .addComponent(pax)))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(submit)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void singleroomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_singleroomActionPerformed
        setSelectedRoomType("Standard - Single Room");
    }//GEN-LAST:event_singleroomActionPerformed

    private void doubleroomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doubleroomActionPerformed
        setSelectedRoomType("Standard - Double Room");
    }//GEN-LAST:event_doubleroomActionPerformed

    private void twinroomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twinroomActionPerformed
        setSelectedRoomType("Standard - Twin Room");
    }//GEN-LAST:event_twinroomActionPerformed

    private void juniorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_juniorActionPerformed
        setSelectedRoomType("Suite - Junior Room");
    }//GEN-LAST:event_juniorActionPerformed

    private void premiumfurnishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_premiumfurnishActionPerformed
        setSelectedRoomType("Deluxe - Premium Furnishing");
    }//GEN-LAST:event_premiumfurnishActionPerformed

    private void wbalconyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wbalconyActionPerformed
        setSelectedRoomType("Deluxe - With Balcony or Patio");
    }//GEN-LAST:event_wbalconyActionPerformed

    private void viewofresortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewofresortActionPerformed
        setSelectedRoomType("Deluxe - View of Resort");
    }//GEN-LAST:event_viewofresortActionPerformed

    private void executiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_executiveActionPerformed
        setSelectedRoomType("Suite - Executive Room");
    }//GEN-LAST:event_executiveActionPerformed

    private void presidentialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_presidentialActionPerformed
        setSelectedRoomType("Suite - Presidential Room");
    }//GEN-LAST:event_presidentialActionPerformed

    private void royalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_royalActionPerformed
        setSelectedRoomType("Suite - Royal Room");
    }//GEN-LAST:event_royalActionPerformed

    private void numberofpaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberofpaxActionPerformed
        try {
            setNumberOfPax(Integer.parseInt(numberofpax.getText()));
        } catch (NumberFormatException e) {
            // Handle invalid input
            numberofpax.setText("");
            System.out.println("Please enter a valid number for Pax.");
        }
        
    

    }//GEN-LAST:event_numberofpaxActionPerformed

    private void doneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneActionPerformed
        result.setText("Room Type: " + getSelectedRoomType() + "\nNumber of Pax: " + getNumberOfPax());
    }//GEN-LAST:event_doneActionPerformed
    
    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_submitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new room().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel choice;
    private javax.swing.JLabel deluxeroom;
    private javax.swing.JButton done;
    private javax.swing.JLabel doubleprice;
    private javax.swing.JRadioButton doubleroom;
    private javax.swing.JRadioButton executive;
    private javax.swing.JLabel executiveprice;
    private javax.swing.JLabel guestchoice;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton junior;
    private javax.swing.JLabel juniorprice;
    private javax.swing.JTextField numberofpax;
    private javax.swing.JLabel pax;
    private javax.swing.JLabel plschoose;
    private javax.swing.JRadioButton premiumfurnish;
    private javax.swing.JLabel premprice;
    private javax.swing.JRadioButton presidential;
    private javax.swing.JLabel presidentialprice;
    private javax.swing.JLabel prices;
    private javax.swing.JTextArea result;
    private javax.swing.JLabel roomreserve;
    private javax.swing.JRadioButton royal;
    private javax.swing.JLabel royalprice;
    private javax.swing.JLabel singleprice;
    private javax.swing.JRadioButton singleroom;
    private javax.swing.JLabel standardroom;
    private javax.swing.JButton submit;
    private javax.swing.JLabel suiteroom;
    private javax.swing.JLabel twinprice;
    private javax.swing.JRadioButton twinroom;
    private javax.swing.JRadioButton viewofresort;
    private javax.swing.JLabel viewprice;
    private javax.swing.JRadioButton wbalcony;
    private javax.swing.JLabel wbalconyprice;
    // End of variables declaration//GEN-END:variables
}
