
public class salads extends javax.swing.JFrame {

    /**
     * Creates new form salads
     */
    public salads() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        CaesarSalad = new javax.swing.JCheckBox();
        ChickenCaesarSalad = new javax.swing.JCheckBox();
        AsianSalad = new javax.swing.JCheckBox();
        ChickenPrawnMangoSalad = new javax.swing.JCheckBox();
        caesarsaladprice = new javax.swing.JLabel();
        chickencaesarsaladprice = new javax.swing.JLabel();
        asiansaladprice = new javax.swing.JLabel();
        chickenprawnprice = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        numberofpcsSalads = new javax.swing.JTextField();
        donesalads = new javax.swing.JButton();
        areaTxt = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        menu = new javax.swing.JButton();
        submitStarter = new javax.swing.JButton();
        freshfrom = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Serif", 3, 48)); // NOI18N
        jLabel1.setText("Salads");

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        CaesarSalad.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        CaesarSalad.setText("Caesar Salad");
        CaesarSalad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaesarSaladActionPerformed(evt);
            }
        });

        ChickenCaesarSalad.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        ChickenCaesarSalad.setText("Chicken Caesar Salad");
        ChickenCaesarSalad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChickenCaesarSaladActionPerformed(evt);
            }
        });

        AsianSalad.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        AsianSalad.setText("Asian Salad");
        AsianSalad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AsianSaladActionPerformed(evt);
            }
        });

        ChickenPrawnMangoSalad.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        ChickenPrawnMangoSalad.setText("Chicken Prawn Mango Salad");
        ChickenPrawnMangoSalad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChickenPrawnMangoSaladActionPerformed(evt);
            }
        });

        caesarsaladprice.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        caesarsaladprice.setText("PhP 199.99");

        chickencaesarsaladprice.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        chickencaesarsaladprice.setText("PHP 259.99");

        asiansaladprice.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        asiansaladprice.setText("PhP 239.99");

        chickenprawnprice.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        chickenprawnprice.setText("PHP 279.99");

        jLabel2.setFont(new java.awt.Font("Serif", 3, 12)); // NOI18N
        jLabel2.setText("pcs:");

        donesalads.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        donesalads.setText("Done");
        donesalads.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donesaladsActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        areaTxt.setViewportView(jTextArea1);

        menu.setText("Menu");

        submitStarter.setText("Submit");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ChickenPrawnMangoSalad, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ChickenCaesarSalad, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CaesarSalad, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AsianSalad, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(caesarsaladprice, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(chickenprawnprice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(asiansaladprice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(chickencaesarsaladprice, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numberofpcsSalads, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(donesalads)
                        .addGap(11, 11, 11)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(menu)
                        .addGap(34, 34, 34)
                        .addComponent(submitStarter))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(311, Short.MAX_VALUE)
                        .addComponent(areaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CaesarSalad)
                    .addComponent(caesarsaladprice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChickenCaesarSalad)
                    .addComponent(chickencaesarsaladprice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AsianSalad)
                    .addComponent(asiansaladprice))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChickenPrawnMangoSalad)
                    .addComponent(chickenprawnprice))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(numberofpcsSalads, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(donesalads))
                .addGap(28, 28, 28)
                .addComponent(areaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(menu)
                    .addComponent(submitStarter))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        freshfrom.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        freshfrom.setText("Fresh from the farm fruits and vegetables delicately prepared the British way.");
        freshfrom.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                freshfromAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(freshfrom))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(freshfrom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void freshfromAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_freshfromAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_freshfromAncestorAdded

    private void CaesarSaladActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaesarSaladActionPerformed

    }//GEN-LAST:event_CaesarSaladActionPerformed

    private void ChickenCaesarSaladActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChickenCaesarSaladActionPerformed

    }//GEN-LAST:event_ChickenCaesarSaladActionPerformed

    private void AsianSaladActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AsianSaladActionPerformed

    }//GEN-LAST:event_AsianSaladActionPerformed

    private void ChickenPrawnMangoSaladActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChickenPrawnMangoSaladActionPerformed

    }//GEN-LAST:event_ChickenPrawnMangoSaladActionPerformed

    private void donesaladsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donesaladsActionPerformed
             StringBuilder summary = new StringBuilder();
    int total = 0;

    // Get the number of pieces entered
    int pcs;
    try {
        pcs = Integer.parseInt(numberofpcsSalads.getText());
    } catch (NumberFormatException e) {
        pcs = 0; // Default to 0 if input is invalid
    }

    // Check which items are selected and build the summary
    if (CaesarSalad.isSelected()) {
        summary.append("Caesar Salad: ").append(pcs).append(" pcs at ₱ 199.99 each\n");
        total += pcs * 199.99;
    }
    if (ChickenCaesarSalad.isSelected()) {
        summary.append("Chicken Caesar Salad: ").append(pcs).append(" pcs at ₱ 259.99 each\n");
        total += pcs * 259.99;
    }
    if (AsianSalad.isSelected()) {
        summary.append("Asian Salad: ").append(pcs).append(" pcs at ₱ 239.99 each\n");
        total += pcs * 239.99;
    }
    if (ChickenPrawnMangoSalad.isSelected()) {
        summary.append("Chicken Prawn Mango Salad: ").append(pcs).append(" pcs at ₱ 279.99 each\n");
        total += pcs * 279.99;
    }

    // Append the total to the summary
    summary.append("Total: ₱ ").append(total).append("\n");

    // Display the summary in the JTextArea
    jTextArea1.setText(summary.toString());
    }//GEN-LAST:event_donesaladsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(salads.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(salads.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(salads.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(salads.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new salads().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox AsianSalad;
    private javax.swing.JCheckBox CaesarSalad;
    private javax.swing.JCheckBox ChickenCaesarSalad;
    private javax.swing.JCheckBox ChickenPrawnMangoSalad;
    private javax.swing.JScrollPane areaTxt;
    private javax.swing.JLabel asiansaladprice;
    private javax.swing.JLabel caesarsaladprice;
    private javax.swing.JLabel chickencaesarsaladprice;
    private javax.swing.JLabel chickenprawnprice;
    private javax.swing.JButton donesalads;
    private javax.swing.JLabel freshfrom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton menu;
    private javax.swing.JTextField numberofpcsSalads;
    private javax.swing.JButton submitStarter;
    // End of variables declaration//GEN-END:variables
}
