
import javax.swing.JOptionPane;

public class wholeResort extends javax.swing.JFrame {

    /**
     * Creates new form wholeResort
     */
    public wholeResort() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        smallCottage = new javax.swing.JRadioButton();
        mediumCottage = new javax.swing.JRadioButton();
        largeCottage = new javax.swing.JRadioButton();
        txtbox = new javax.swing.JComboBox<>();
        cottageButton = new javax.swing.JButton();
        cottagePrice = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        standardRoom = new javax.swing.JLabel();
        singleRoom1 = new javax.swing.JRadioButton();
        doubleRoom1 = new javax.swing.JRadioButton();
        twinRoom1 = new javax.swing.JRadioButton();
        deluxeRoom = new javax.swing.JLabel();
        premiumRoom = new javax.swing.JRadioButton();
        balconyRoom = new javax.swing.JRadioButton();
        viewRoom = new javax.swing.JRadioButton();
        juniorRoom = new javax.swing.JRadioButton();
        exeRoom = new javax.swing.JRadioButton();
        royalRoom = new javax.swing.JRadioButton();
        suiteRoom = new javax.swing.JLabel();
        presRoom = new javax.swing.JRadioButton();
        stdButton = new javax.swing.JButton();
        stdPrice = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        allReceipt = new javax.swing.JTextArea();
        completeButton = new javax.swing.JButton();
        logSubmit = new javax.swing.JButton();
        logMenu = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtdate = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNumber = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Serif", 2, 24)); // NOI18N
        jLabel1.setText("Whole Resort Reservation");

        jPanel2.setBackground(java.awt.SystemColor.controlLtHighlight);

        jLabel4.setText("Cottage");

        buttonGroup2.add(smallCottage);
        smallCottage.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        smallCottage.setText("Small Cottage");
        smallCottage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smallCottageActionPerformed(evt);
            }
        });

        buttonGroup2.add(mediumCottage);
        mediumCottage.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        mediumCottage.setText("Medium Cottage");
        mediumCottage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mediumCottageActionPerformed(evt);
            }
        });

        buttonGroup2.add(largeCottage);
        largeCottage.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        largeCottage.setText("Large Cottage");
        largeCottage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                largeCottageActionPerformed(evt);
            }
        });

        txtbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "12 hours", "24 hours" }));

        cottageButton.setText("✅");
        cottageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cottageButtonActionPerformed(evt);
            }
        });

        cottagePrice.setText("₱: ");
        cottagePrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cottagePriceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cottageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(largeCottage, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(smallCottage, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mediumCottage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtbox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(36, 36, 36)
                .addComponent(cottagePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(smallCottage)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mediumCottage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(largeCottage)
                .addGap(18, 18, 18)
                .addComponent(txtbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cottageButton)
                    .addComponent(cottagePrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(127, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("SansSerif", 0, 8)); // NOI18N
        jLabel9.setText("Select Room Type:");

        jPanel3.setBackground(java.awt.SystemColor.controlLtHighlight);

        standardRoom.setText("Standard Room:");

        buttonGroup1.add(singleRoom1);
        singleRoom1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        singleRoom1.setText("Single Room");
        singleRoom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                singleRoom1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(doubleRoom1);
        doubleRoom1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        doubleRoom1.setText("Double Room");

        buttonGroup1.add(twinRoom1);
        twinRoom1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        twinRoom1.setText("Twin Room");
        twinRoom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twinRoom1ActionPerformed(evt);
            }
        });

        deluxeRoom.setText("Deluxe Room:");

        buttonGroup1.add(premiumRoom);
        premiumRoom.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        premiumRoom.setText("Premium Furnishing");
        premiumRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                premiumRoomActionPerformed(evt);
            }
        });

        buttonGroup1.add(balconyRoom);
        balconyRoom.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        balconyRoom.setText("W/balcony or Patio");
        balconyRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balconyRoomActionPerformed(evt);
            }
        });

        buttonGroup1.add(viewRoom);
        viewRoom.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        viewRoom.setText("View of Resort");
        viewRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewRoomActionPerformed(evt);
            }
        });

        buttonGroup1.add(juniorRoom);
        juniorRoom.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        juniorRoom.setText("Junior Room");
        juniorRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                juniorRoomActionPerformed(evt);
            }
        });

        buttonGroup1.add(exeRoom);
        exeRoom.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        exeRoom.setText("Executive Room");

        buttonGroup1.add(royalRoom);
        royalRoom.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        royalRoom.setText("Royal");
        royalRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                royalRoomActionPerformed(evt);
            }
        });

        suiteRoom.setText("Suite Room:");

        buttonGroup1.add(presRoom);
        presRoom.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        presRoom.setText("Presidential Room");
        presRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                presRoomActionPerformed(evt);
            }
        });

        stdButton.setText("✅");
        stdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stdButtonActionPerformed(evt);
            }
        });

        stdPrice.setText("₱: ");
        stdPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stdPriceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(deluxeRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(standardRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(suiteRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(balconyRoom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(juniorRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(twinRoom1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(doubleRoom1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(singleRoom1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(premiumRoom)
                            .addComponent(viewRoom)
                            .addComponent(exeRoom)
                            .addComponent(presRoom)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(royalRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(stdButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(stdPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 17, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(singleRoom1)
                    .addComponent(standardRoom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(doubleRoom1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(twinRoom1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(premiumRoom)
                    .addComponent(deluxeRoom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(balconyRoom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewRoom)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(juniorRoom)
                    .addComponent(suiteRoom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exeRoom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(presRoom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(royalRoom)
                    .addComponent(stdButton)
                    .addComponent(stdPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        jLabel10.setFont(new java.awt.Font("SansSerif", 0, 8)); // NOI18N
        jLabel10.setText("Select Cottage Type:");

        jLabel14.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        jLabel14.setText("Receipt...");

        allReceipt.setColumns(20);
        allReceipt.setRows(5);
        jScrollPane3.setViewportView(allReceipt);

        completeButton.setBackground(new java.awt.Color(204, 255, 255));
        completeButton.setText("Complete");
        completeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                completeButtonActionPerformed(evt);
            }
        });

        logSubmit.setText("Submit");
        logSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logSubmitActionPerformed(evt);
            }
        });

        logMenu.setText("Menu");
        logMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logMenuActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel15.setText("Click Menu when you Submit:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jLabel11.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel11.setText("Full date of reservation: ");

        txtdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdateActionPerformed(evt);
            }
        });

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel2.setText("Name:");

        txtNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumberActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel3.setText("Number:");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 18, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10)
                                .addGap(367, 367, 367))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(159, 159, 159)
                                .addComponent(logSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(logMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(completeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel15)
                                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(80, 80, 80)))))
                        .addGap(1, 1, 1)))
                .addGap(33, 33, 33))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 300, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(completeButton)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(logSubmit)
                                    .addComponent(logMenu))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stdButtonActionPerformed
        // TODO add your handling code here:
      String price = "₱: ";

    // Check which radio button is selected and set the price accordingly
    if (smallCottage.isSelected()) {
        price += " 1000"; // Price for Single Room
    } else if (mediumCottage.isSelected()) {
        price += " 2500"; // Price for Double Room
    } else if (largeCottage.isSelected()) {
        price += " 8000"; // Price for Twin Room
    } 
    else if (premiumRoom.isSelected()) {
        price += " 6000"; // Price for Twin Room
    } 
    else if (balconyRoom.isSelected()) {
        price += " 6500"; // Price for Twin Room
    } 
    else if (viewRoom.isSelected()) {
        price += " 7000"; // Price for Twin Room
    }
    else if (juniorRoom.isSelected()) {
        price += " 8000"; // Price for Twin Room
    }
    else if (exeRoom.isSelected()) {
        price += " 8500"; // Price for Twin Room
    }
    else if (presRoom.isSelected()) {
        price += " 9000"; // Price for Twin Room
    }
    else if (royalRoom.isSelected()) {
        price += " 9500"; // Price for Twin Room
    }
     else {
        price += " 0"; // Default if no room is selected
    }
     stdPrice.setText(price);
  
    }//GEN-LAST:event_stdButtonActionPerformed

    private void txtNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumberActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void smallCottageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smallCottageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_smallCottageActionPerformed

    private void largeCottageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_largeCottageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_largeCottageActionPerformed

    private void stdPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stdPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stdPriceActionPerformed

    private void singleRoom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_singleRoom1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_singleRoom1ActionPerformed

    private void twinRoom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twinRoom1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_twinRoom1ActionPerformed

    private void premiumRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_premiumRoomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_premiumRoomActionPerformed

    private void viewRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewRoomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewRoomActionPerformed

    private void juniorRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_juniorRoomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_juniorRoomActionPerformed

    private void royalRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_royalRoomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_royalRoomActionPerformed

    private void presRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_presRoomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_presRoomActionPerformed

    private void balconyRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balconyRoomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_balconyRoomActionPerformed

    private void cottageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cottageButtonActionPerformed
         String price = "₱: ";
    int durationMultiplier = 1; // Default multiplier for price

    // Check the selected duration from the combo box
    String selectedDuration = (String) txtbox.getSelectedItem();
    if (selectedDuration.equals("24 hours")) {
        durationMultiplier = 2; // Double the price for 24 hours
    }

    // Check which radio button is selected and set the price accordingly
    if (smallCottage.isSelected()) {
        price += (700 * durationMultiplier); // Price for Small Cottage
    } else if (mediumCottage.isSelected()) {
        price += (900 * durationMultiplier); // Price for Medium Cottage
    } else if (largeCottage.isSelected()) {
        price += (1400 * durationMultiplier); // Price for Large Cottage
    } else {
        price += "0"; // Default if no cottage is selected
    }

    // Set the calculated price in the cottagePrice text field
    cottagePrice.setText(price);
    }//GEN-LAST:event_cottageButtonActionPerformed

    private void cottagePriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cottagePriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cottagePriceActionPerformed

    private void mediumCottageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mediumCottageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mediumCottageActionPerformed

    private void txtdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdateActionPerformed

    private void completeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_completeButtonActionPerformed
       // Retrieve user inputs
    String name = txtName.getText();
    String number = txtNumber.getText();
    String date = txtdate.getText();
    String stdPriceValue = stdPrice.getText().replace("₱: ", "").trim(); // Remove currency symbol and whitespace
    String cottagePriceValue = cottagePrice.getText().replace("₱: ", "").trim(); // Remove currency symbol and whitespace

    // Convert prices to integers for calculation
    int stdPriceInt = Integer.parseInt(stdPriceValue);
    int cottagePriceInt = Integer.parseInt(cottagePriceValue);

    // Calculate total price
    int totalPrice = stdPriceInt + cottagePriceInt;

    // Format the receipt
    String receipt = "Here's your Receipt!\n";
    receipt += "=====================\n";
    receipt += "Name: " + name + "\n";
    receipt += "Number: " + number + "\n";
    receipt += "=====================\n";
    receipt += "Date of Reservation: " + date + "\n";
    receipt += "Standard Room Price: ₱" + stdPriceValue + "\n";
    receipt += "Cottage Price: ₱" + cottagePriceValue + "\n";
     receipt += "=====================\n";
    receipt += "Total Price: ₱" + totalPrice + "\n"; // Display total price
    receipt += "=====================\n";

    // Display the receipt in the allReceipt text area
    allReceipt.setText(receipt);
    }//GEN-LAST:event_completeButtonActionPerformed

    private void logSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logSubmitActionPerformed
        new Menu().setVisible(true);
        JOptionPane.showMessageDialog(this, "Reserve Successful", "Confirmation", JOptionPane.INFORMATION_MESSAGE);
        // TODO add your handling code here:
    }//GEN-LAST:event_logSubmitActionPerformed

    private void logMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logMenuActionPerformed
        // TODO add your handling code here:
        new Menu().setVisible(true);
    }//GEN-LAST:event_logMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(wholeResort.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(wholeResort.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(wholeResort.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(wholeResort.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new wholeResort().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea allReceipt;
    private javax.swing.JRadioButton balconyRoom;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton completeButton;
    private javax.swing.JButton cottageButton;
    private javax.swing.JTextField cottagePrice;
    private javax.swing.JLabel deluxeRoom;
    private javax.swing.JRadioButton doubleRoom1;
    private javax.swing.JRadioButton exeRoom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton juniorRoom;
    private javax.swing.JRadioButton largeCottage;
    private javax.swing.JButton logMenu;
    private javax.swing.JButton logSubmit;
    private javax.swing.JRadioButton mediumCottage;
    private javax.swing.JRadioButton premiumRoom;
    private javax.swing.JRadioButton presRoom;
    private javax.swing.JRadioButton royalRoom;
    private javax.swing.JRadioButton singleRoom1;
    private javax.swing.JRadioButton smallCottage;
    private javax.swing.JLabel standardRoom;
    private javax.swing.JButton stdButton;
    private javax.swing.JTextField stdPrice;
    private javax.swing.JLabel suiteRoom;
    private javax.swing.JRadioButton twinRoom1;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNumber;
    private javax.swing.JComboBox<String> txtbox;
    private javax.swing.JTextField txtdate;
    private javax.swing.JRadioButton viewRoom;
    // End of variables declaration//GEN-END:variables
}
